### ISSUE TITLE
Add factory class for spring-integration-redis

### ISSUE THREAD

**Issue by daniel-frank** [spring-projects/spring-integration-java-dsl#102]
Please, add factory class for spring-integration-redis (RedisQueueInboundGateway, RedisQueueOutboundGateway, ...) support.
Relates to: http://stackoverflow.com/questions/38863110/factory-class-for-spring-integration-redis-components

**Comment by artembilan** [comment]
Also consider to investigate Embedded Redis for tests.
See https://github.com/spring-projects/spring-boot/pull/6497.

**Comment by artembilan** [comment]
Closed in favor of https://jira.spring.io/browse/INT-4165 since all new features are considered in the Spring Integration Core already for it version 5.0.
