### ISSUE TITLE
Detect @Scope on IntegrationFlow

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-integration-java-dsl#104]
Consider detecting `@Scope` on an `IntegrationFlow` bean.

Two recent SO questioners [here](http://stackoverflow.com/questions/39081924/config-refresh-isnt-working-inside-route-declaration) and [here](http://stackoverflow.com/questions/39087914/spring-integration-dsl-make-feed-flow-work/39088075#39088075) were trying to use scopes on Integration flows. This won't work because the internal beans created by the flow won't be in the scope.

I am not sure if we should reject the `@Bean` or just detect and log - there may be some unkown custom scope that would work, but scopes such as prototype, session, request certainly won't work.

**Comment by artembilan** [comment]
Well, actually it won't work even on simple `@ServiceActivator` with `@Bean`.
I'm fully not sure what you would like to achieve with this issue...

OTOH we can configure `IntegrationFlow` as a `@Service`: https://github.com/spring-projects/spring-integration-java-dsl/blob/master/src/test/java/org/springframework/integration/dsl/test/flowservices/FlowServiceTests.java.

Is there somewhere something similar to investigate?

**Comment by garyrussell** [comment]
I am just floating the idea of (somehow) checking for invalid configurations to avoid these SO questions from popping up. Feel free to close if you don't think it's possible.

**Comment by artembilan** [comment]
Yeah... I just don't know what to say.
More and more stuff the last time which I'm not aware.
Feels useless :cry: 

Although for this one to detect the `scope` we can use `ConfigurableListableBeanFactory.getBeanDefinition(beanName).getScope()`.
And if it isn't `ConfigurableBeanFactory.SCOPE_SINGLETON` reject bean initialization.

Is that what are you looking for ?

**Comment by garyrussell** [comment]
Something like that but as I said above, I am not sure whether we should reject or just log.
