### ISSUE TITLE
Autostartup(false) is not working properly

### ISSUE THREAD

**Issue by SonalGuptaGemini** [spring-projects/spring-integration-java-dsl#105]
Hello everyone.. 

I have a `JmsMessageDrivenChannelAdapter` which wraps up a `DefaultMessageListenerContainer` and sets the `autostartup` as `false`. 
eg -
```
@Bean
@Qualifier("endpointAdapter")
public JmsMessageDrivenChannelAdapter endpointAdapter(....){
      return Jms.messageDriverChannelAdapter(endPointContainer).autoStartup(false).get();
}
```
Although the `DefaultLifecycleProcessor` does not starts the adapter(`endpointAdapter`) but when I push a message on the queue bound with the container(`endPointContainer`), my code is still picking up the message from the queue..

Can anyone please help me as I am totally stuck here... :( :(

Thanks

**Comment by artembilan** [comment]
That's correct because an external container lifecycle lives independently of the Channel Adapter.

To fix your problem you have to declare `autoStartup = false` and for the `endPointContainer`, too.

Do address that in the Framework I've just raised this one: https://jira.spring.io/browse/INT-4102.

We really should do `this.messageListenerContainer.setAutoStartup(false);` in the adapter and rely only on its lifecycle and don't let container to be started independently.

**Comment by SonalGuptaGemini** [comment]
Thanks for your response..
But one thing to mention here.
If I set "Jms.messageDriverChannelAdapter(endPointContainer).autoStartup(true)get():" 

And then i explicitly, through a message flow, stop the adapter like this- endpointAdapter.stop()

, this will stop the adapter. Now if I push any message on the queue, it will not be picked up by my code. Why does this happens then? Because now also the container is running in its own life cycle..

It will be great if you can clear my doubt on this..

Thanks

}

**Comment by artembilan** [comment]
Out of topic: your post are in very low level. It's hard to read them. Please, be sure that they well formed and have a good grammar. Plus study how to [comment](https://guides.github.com/features/mastering-markdown/) properly on GitHub.

Now on the matter. The `JmsMessageDrivenEndpoint` has a code like:
```
protected void doStart() {
		this.listener.start();
		if (!this.listenerContainer.isRunning()) {
			this.listenerContainer.start();
		}
	}

	@Override
	protected void doStop() {
		this.listenerContainer.stop();
		this.listener.stop();
}
```
So, when we interact with the adapter lifecycle, it involves the container as well.

The only problem we have that container is not in stopped state from the beginning. At runtime the works correctly: stopping/starting adapter has effect on the container, too.

**Comment by SonalGuptaGemini** [comment]
Sure..i'll go through the guidelines for posting a comment on git hub :)..
And thanks for the explanation.. it worked for me..

**Comment by artembilan** [comment]
Great! Closed in favor of mentioned JIRA above. We will upgrade Java DSL 1.2 to the SI-4.3.2 to make a fix aboard silently.

**Comment by SonalGuptaGemini** [comment]
What fix are you talking about?

**Comment by artembilan** [comment]
This one: https://github.com/spring-projects/spring-integration/pull/1880.

The container lifecycle must be fully aligned with the adapter lifecycle. Otherwise we have this confusing inconsistency.

**Comment by SonalGuptaGemini** [comment]
yes definitely.. anyways thanks for all the help :)

**Comment by SonalGuptaGemini** [comment]
Sorry but one last question.. By when this fix will be available for all? Actually I am in the mid of implementing this start/stop functionality, so if this fix is going be released soon, it will be good to go with the updated lifecycle of the adapter..

**Comment by garyrussell** [comment]
The fix is merged; we expect to release 4.3.2 including the fix within about a week.

**Comment by artembilan** [comment]
Yep! And exactly that time I expect to have Java DSL 1.2 RC1.

**Comment by SonalGuptaGemini** [comment]
Oh Great! Thanks!
