### ISSUE TITLE
Kafka09 Message Driven Channel Adapter Typo

### ISSUE THREAD

**Issue by magiccrafter** [spring-projects/spring-integration-java-dsl#121]
First, thank you for the amazing work you've done and keep on doing.

The issue is that in in Kafka09 class, the methods for the message driven channel adaptor are with a typo
Instead of 
messageDrive**r**ChannelAdapter
they have to be 
messageDrive**n**ChannelAdapter

**Comment by artembilan** [comment]
Yeah! 
Good catch :smile: !

Since that class has been introduced in the version `1.2` we can simply to rename them to the proper name.

Feel free to provide fix as a contribution!

**Comment by magiccrafter** [comment]
Cool. I will. 10x
