### ISSUE TITLE
InBoundChannelAdapter using Annotation

### ISSUE THREAD

**Issue by parmarsanjay** [spring-projects/spring-integration-java-dsl#138]
I am trying to develop solution similar to this 

http://stackoverflow.com/questions/11563469/spring-integration-cron-quartz-in-cluster

I am defining my inbound channel adapter using annotation. How do I get reference to Inbound Channel Adapter bean so that I can do start / stop as suggested by Gary.

**Comment by artembilan** [comment]
I guess you are using `@InboundChannelAdapter`. 
The algorithm to build a `bean name` for automatically created endpoints is like:

> The bean names are generated with this algorithm: * The `MessageHandler` (`MessageSource`) `@Bean` gets its own standard name from the method name or name attribute on the `@Bean`. This works like there is no Messaging Annotation on the `@Bean` method. * The `AbstractEndpoint` bean name is generated with the pattern: `[configurationComponentName].[methodName].[decapitalizedAnnotationClassShortName]`. For example the endpoint (`SourcePollingChannelAdapter`) for the `consoleSource()` definition above gets a bean name like: `myFlowConfiguration.consoleSource.inboundChannelAdapter`.

See [Reference Manual](http://docs.spring.io/spring-integration/reference/html/configuration.html#annotations_on_beans) for more information.

**Comment by artembilan** [comment]
Looks like this is your StackOverflow quesiton: http://stackoverflow.com/questions/40558655/spring-cloud-stream-quartz.

So, closing this issue in favor of that and answering there.
