### ISSUE TITLE
Spring 5 Compatibility for Java DSL? 

### ISSUE THREAD

**Issue by springframeworkguru** [spring-projects/spring-integration-java-dsl#141]
I'm trying to upgrade an existing Spring Boot / Integration project to Spring Boot 2 (Spring 5) and this class is not found: org.springframework.integration.expression.IntegrationEvaluationContextAware

I see it has been deprecated in 4, and not avail in 5. 

I tried the snapshot version of the java-dsl (1.2.2.BUILD-SNAPSHOT), no luck. 

Has this not been addressed in the Java dsl yet?

**Comment by garyrussell** [comment]
The DSL is being merged into the core Spring Integration project, we no longer use that interface we get the context via a utility class.

You no longer need the separate artifact for the DSL.

See [the Spring Integration migration guide](https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-4.3-to-5.0-Migration-Guide#java-dsl).

**Comment by springframeworkguru** [comment]
Ah - thanks Gary! Looking forward to kicking the tires on all the new stuff in 5.
