### ISSUE TITLE
No reply produced by handler 'org.springframework.integration.transformer.messagetransforminghandler#3', and its 'requiresreply' property is set to true.

### ISSUE THREAD

**Issue by SonalGuptaGemini** [spring-projects/spring-integration-java-dsl#147]
Hi,

I am using spring DSL. I have an error channel[EC] associated with my message flow, so that whenever my code fails at any point, it should be redirected to this EC.
....
```
.from("erroChannel")
.handle(outboundadapter...).destination(queueName).get();
```

Now whenever my code breaks in the Junit, it does comes to the flow, but throws this message

> No reply produced by handler 'org.springframework.integration.transformer.messagetransforminghandler#3', and its 'requiresreply' property is set to true.

Can anyone please help me in understanding this error message?

**Thanks in anticipation**

**Comment by artembilan** [comment]
That error means that your custom code for the `.transform()` returns `null`, when transformer pattern requires non-null reply.

It is not clear yet how it relates to your error handling, but looks like there is no problem with the Framework and your question should be moved to the StackOverflow with more useful info to determine what's going on.
Thanks
