### ISSUE TITLE
What is XSD validator alternative in Java DSL?

### ISSUE THREAD

**Issue by noorulhaq** [spring-projects/spring-integration-java-dsl#148]
In spring integration XML-based flow definition we have **int-xml:validating-filter** for validating XML against XSD. What is the alternative for this in JavaDSL?

**Comment by artembilan** [comment]
The class behind `<int-xml:validating-filter>` is:
```
<xsd:documentation>
		Configures a Consumer Endpoint for the
		'org.springframework.integration.filter.MessageFilter'
		with an 'org.springframework.integration.xml.selector.XmlValidatingMessageSelector'
</xsd:documentation>
```

So, the equivalent for the Java DSL is like:
```
.filter(new XmlValidatingMessageSelector(xsdResource, XmlValidatingMessageSelector.SchemaType.XML_SCHEMA))
```

Since that look pretty easy we don't see reason to add some first class support for the Java DSL per se.

Hope that makes sense to you.

Such a question belongs to StackOverflow though...

**Comment by noorulhaq** [comment]
Thanks for your reply.

The reason I asked this question because I was expecting to have Java DSL more explicit and declarative, which unfortunately after seeing your reply I am a bit disappointed. I can see that in the documentation, Spring DSL provides a more declarative approach for **Transformers**, as shown below:
'''java
Transformers.xpath("/root/myJson", XPathEvaluationType.STRING_RESULT)
'''
Even above can be shortened to a more declarative function. I was expecting something similar to that as **Filters**, hence, I raised the question. Anyways, if we really want to call it DSL then it should look like a DSL, otherwise, it is better to put a disclaimer at the top in the documentation.

**Comment by noorulhaq** [comment]
Oh, by the way, it is very trivial to label the issue as a question, below link is for your reference.
https://github.com/vavr-io/vavr/labels/question

**Comment by artembilan** [comment]
No-op.

I understand your "fluent API" concern, but even that `Transformers.xpath()` has been lost after moving DSL to the Spring Integration Core 5.0. Just because we can't bring SI-XML dependency into Core to leverage that still simple `XPathTransformer` class.

I think we can come up with something like an `Xml` factory in the SI-XML module (similar to the `Amqp`, `Jms`, `Scripts` etc.) and bring "more declarative functions" there for use-cases like yours.

Feel free to open a [JIRA](https://jira.spring.io/browse/INT) on the matter and even consider a [Contribution](https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc).

At least, please, share your vision: any way everything we do here is just for your, community convenience.

We don't use GH for question/answer communication. This is only for bugs and feature requests.
We might not be available, but in the public forums some other people may answer similar questions.

**Comment by noorulhaq** [comment]
That is very sad, but I liked your idea of having the helper/ declarative functions inside the respective modules. 

My vision of a good DSL is to just specify _"**what** need to be done, not **how** it can be done"_. 

I really liked what JavaDSL brings on the table, but with such minor improvements, we can make it more readable and effortless. 

Moreover, having such declarative functions adds another layer of abstraction, that gives the opportunity to change the implementation without changing the DSL.

I hope we are still on good terms :)

**Comment by artembilan** [comment]
OK. Great! 

To be honest I'm not fully sure that I got your "declarative functions" term.

Would you mind to elaborate more? At least with some pseudo code what that could be.

Thank you for such a feedback!

**Comment by noorulhaq** [comment]
By declarative function, I was referring to helper functions that declare _"**what** need to be done"_

Below is a rough cut from an application I am writing for R&D.

```java

@Autowired
public IntegrationFlowContext integrationFlowContext;

@Value("classpath:reservation.xsd")
public Resource xsdSchema;

@StreamListener
public void reservationStream(@Input(Sink.INPUT) Flux<Message<?>> reservations) {

	Flux<Message<?>> flux =  reservations.doOnNext(reservation -> System.out.println(" Before -> "+ reservation));

	IntegrationFlow validationAndTransformation = from(flux).<String>filter(xml -> xmlValidation(xsdSchema,xml))
			.<String, Reservation>transform(reservation -> xmlToObject(reservation,Reservation.class))
			.<Reservation>handle((p, h) -> {
				acknowledge(h);
				return p;
			})
			.channel(reservationsChannel())
			.get();

	Flux.from(toPublisher(reservationsChannel()))
			.doOnNext(reservation -> System.out.println(" After -> "+ reservation)).subscribe();

	this.integrationFlowContext.registration(validationAndTransformation).register();
}

@Bean
public QueueChannel reservationsChannel(){
	return new QueueChannel();
}
```
Here **xmlValidation, xmlToObject, and acknowledge** are all helper functions, making the whole flow more declartive and readable.

By the way, what is your opinion about backpressure management here, will it be still honored or not?

**Comment by artembilan** [comment]
OK. Thank you for your comprehensive description!

Well, sounds like my suggestion for `Xml` factory is fully meeting your requirements:
```
class Xml {

    public static XmlValidatingMessageSelector validation(Resource schema) {
           ...
    }

}
```
and usage would be like:

```
.filter(Xml.validation(xsdSchema))
```


The `ItengrationFlowDefinition` has `toReactivePublisher()`.

To make it fully back-pressured you should use:
```
.channel(Channels.flux())
```
in between EIP-methods.

Actually your sample is very cool and we will think with the team how to make `(@Input(Sink.INPUT) Flux<Message<?>>` and `return IntegrationFlow` as a good fusion in the next SCSt generation. 😄 

/CC @mbogoevici

**Comment by noorulhaq** [comment]
With regard to backpressure, I tried what you suggested to me, but I am now receiving below error:

```
MessageDeliveryException: Dispatcher has no subscribers for channel 'application:8082.input'.
```
```java
Publisher<Message<Reservation>> validationAndTransform = from(reservations.doOnNext(reservation -> System.out.println(" Before -> "+ reservation)))
		.<String>filter(xml -> xmlValidation(xsdResource,xml))
		.<String, Reservation>transform(reservation -> xmlToObject(reservation,Reservation.class))
		.handle((p, h) -> {
			acknowledge(h);
			return p;
		})
		.toReactivePublisher();

Flux.from(validationAndTransform)
		.doOnNext(reservation -> System.out.println(" After -> "+ reservation)).subscribe();
```

**Comment by artembilan** [comment]
Your `this.integrationFlowContext.registration(validationAndTransformation).register();` is still needed. That `validationAndTransform` can be cast to `IntegrationFlow`. The `toReactivePuvlisher()` returns `PublisherIntegrationFlow`. 

The `IntegrationFlow` must be registered as a bean anyway.

**Comment by artembilan** [comment]
Yes, `Channels::reactive` was correct, but in the latest Milestone 4 it has been renamed to `flux()` to closely reflect the implementation.

**Comment by noorulhaq** [comment]
Thanks for your reply.

Strange, to me with `spring-integration-core` version `5.0.0.M4`, `toReactivePuvlisher` returns `Publisher<Message<?>>` not `PublisherIntegrationFlow`.  

Am I missing something here?

**Comment by artembilan** [comment]
No, that is true. This is a code from there:
```
public <T> Publisher<Message<T>> toReactivePublisher() {
	...

	return new PublisherIntegrationFlow<>(this.integrationComponents, publisher);
}
```

Having your use-case I think we really should make that `PublisherIntegrationFlow` as public and return its type from that method. It is a `Publisher` and `IntegrationFlow` at the same time.

**Comment by noorulhaq** [comment]
Just one more feedback before you decide to make `PublisherIntegrationFlow` public.

I have tried below code with version `5.0.0.M4` and it just does not process any message, but when I tried same code with version `5.0.0.M3` (substituting flux to reactor) it works perfect.
```java
Object validationAndTransform = from(reservations.doOnNext(reservation -> System.out.println(" Before -> "+ reservation)))
	.<String>filter(xml -> xmlValidation(xsdResource,xml))
	.channel(Channels::flux)
	.<String, Reservation>transform(reservation -> xmlToObject(reservation,Reservation.class))
	.channel(Channels::flux)
	.handle((p, h) -> {
		acknowledge(h);
		return p;
	}).toReactivePublisher();

Flux.from((Publisher)validationAndTransform)
		.doOnNext(reservation -> System.out.println(" After -> "+ reservation)).subscribe();

this.integrationFlowContext.registration((IntegrationFlow)validationAndTransform).register();
```

**Comment by artembilan** [comment]
Sounds creepy, @noorulhaq ,

Would you mind to come up with the simplest test-case to play from our side?

Thanks

**Comment by noorulhaq** [comment]
Hi,

Sorry for late reply. Actually, I got busy with something else. Anyway, below is the code snippet and when I use version `5.0.0.M4` it throws following exception on conversion of `PublisherIntegrationFlow` to `Flux`.

```
Caused by: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: reactor.core.publisher.FluxSink.next(Ljava/lang/Object;)Lreactor/core/publisher/FluxSink;
	at org.springframework.integration.channel.MessageChannelReactiveUtils$SubscribableChannelPublisherAdapter.lambda$subscribe$1(MessageChannelReactiveUtils.java:84) ~[spring-integration-core-5.0.0.M4.jar:5.0.0.M4]
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:92) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.integration.channel.MessageChannelReactiveUtils$SubscribableChannelPublisherAdapter.subscribe(MessageChannelReactiveUtils.java:89) ~[spring-integration-core-5.0.0.M4.jar:5.0.0.M4]
	at org.springframework.integration.dsl.PublisherIntegrationFlow.subscribe(PublisherIntegrationFlow.java:45) ~[spring-integration-core-5.0.0.M4.jar:5.0.0.M4]
```
An below is the code.

```java
private IntegrationFlow blackList(){
	return flow -> flow
			.<Reservation>handle((r,h)-> ImmutableReservation.copyOf(r)
					.withIsBlacklisted(true))
			.channel(aggregationChannel());
}

private IntegrationFlow overstay(){
	return flow -> flow
			.<Reservation>handle((r,h)-> ImmutableReservation.copyOf(r)
					.withIsOverstaying(true))
			.channel(aggregationChannel());
}

@StreamListener
public void reservationStream(@Input(Sink.INPUT) Flux<Message<?>> reservations) {

	Object validationAndTransform = from(reservations.doOnNext(reservation -> System.out.println(" Before -> "+ reservation)))
		.<String>filter(xml -> xmlValidation(xsdResource,xml))
		.channel(Channels::reactive)
		.<String, Reservation>transform(reservation -> xmlToObject(reservation,Reservation.class))
		.channel(Channels::reactive)
		.publishSubscribeChannel(Executors.newFixedThreadPool(4), spec -> spec.applySequence(true)
					.subscribe(blackList())
					.subscribe(overstay())
				)
			.channel(aggregationChannel())
			.resequence()
			.channel(Channels::reactive)
			.aggregate(spec -> spec.releaseStrategy(g->g.size()==3))
			.<List<Reservation>>handle((p, h) ->
				p.stream()
						.skip(1)
						.reduce((r1,r2)->ImmutableReservation.copyOf(p.get(0))
								.withIsBlacklisted(r1.isBlacklisted()|r2.isBlacklisted())
								.withIsOverstaying(r1.isOverstaying()|r2.isOverstaying()))
			)
			.publishSubscribeChannel(spec ->
					spec.subscribe(flow ->
							flow.handle(KafkaUtils::acknowledge)))
			.toReactivePublisher();

	Flux.from((Publisher<Message<Optional<Reservation>>>)validationAndTransform)
			.publishOn(Schedulers.single())
			.map(p -> p.getPayload().get())
			.buffer(Duration.ofSeconds(7))
			.map(rl -> {
				Map<String,Long> stats = new HashMap();
				stats.put("blacklistCount", Long.valueOf(rl.stream().filter(r -> r.isBlacklisted()).count()));
				stats.put("overstayCount", Long.valueOf(rl.stream().filter(r -> r.isOverstaying()).count()));
				return stats;
			})
			.doOnNext(reservation -> System.out.println(" After -> "+ reservation))
			.subscribe();

	this.integrationFlowContext.registration((IntegrationFlow)validationAndTransform).register();
}

@Bean
public ReactiveChannel aggregationChannel(){
	return new ReactiveChannel();
}
```
**To be honest, the more I am working with JavaDSL the more I am becoming fond of it. The amalgamation of  JavaDSL with Reactive is amazing. If we have Reactive Kafka also onboard then this it will be awesome**

Still, I have some doubt about it, with the use of publish-subscriber is the backpressure still intact or not. 

Also, give your general opinion about the code snippet above. I mean what can be improved or is bad.

**Comment by artembilan** [comment]
The error `java.lang.NoSuchMethodError: reactor.core.publisher.FluxSink.next(Ljava/lang/Object;)` means that you use the Reactor version which isn't compatible with Spring Integration 5.0 M4.

The publish-subscriber isn't back-pressured. It has fully different purpose. Especially when you configure it is with `TaskExecutor`. The new `FluxMessageChannel` is fully based on the natural back-pressure from the underlying `FluxSink` . So, all your subscribers to this channel will get publish-subscribe distribution by the `Flux` logic.

Yes, we have plans to add Reactor Kafka to the Spring Kafka 2.0 and, therefore, to Spring Integration Kafka 3.0. Spring integration 5.0 should get some love with the Reactive source connection though, but that already might be just a matter of the new `ReactiveKafkaMessageDrivenChannelAdapter` to check the `outputChannel` type and subscriber to the `Publisher` from the Reactor Kafka.

Well, your sample is very cool. It's a bit unclear, but I like your idea about distinguishing sub-flows to separate `private` method.

I might apply your way and override [Cafe Demo](https://github.com/spring-projects/spring-integration-samples/blob/master/dsl/cafe-dsl/src/main/java/org/springframework/integration/samples/dsl/cafe/lambda/Application.java#L83) sample to more functional style 😄

**Comment by noorulhaq** [comment]
Thanks for your detail reply. 

Unfortunately, I am now struggling with another library compatibility issue. As per the pom file, the compatible reactor version with `5.0.0.M4` is `3.1.0.M1`, but after adding this as a dependency, this line `this.integrationFlowContext.registration((IntegrationFlow)validationAndTransform).register()` now gives me below error:

```
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
	at org.springframework.cloud.stream.binding.StreamListenerAnnotationBeanPostProcessor.invokeSetupMethodOnListenedChannel(StreamListenerAnnotationBeanPostProcessor.java:294) ~[spring-cloud-stream-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	... 29 common frames omitted
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: reactor/core/Cancellation
	at org.springframework.cloud.stream.reactive.MessageChannelToInputFluxParameterAdapter.lambda$adapt$2(MessageChannelToInputFluxParameterAdapter.java:67) ~[spring-cloud-stream-reactive-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:90) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
	at reactor.core.publisher.FluxPublish.connect(FluxPublish.java:98) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
	at reactor.core.publisher.FluxAutoConnect.subscribe(FluxAutoConnect.java:62) ~[reactor-core-3.1.0.M1.jar:3.1.0.M1]
```
Would you please share the POM file that has comptiable versions defined?

**Comment by artembilan** [comment]
```
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: reactor/core/Cancellation
	at org.springframework.cloud.stream.reactive.MessageChannelToInputFluxParameterAdapter.lambda$adapt$2(MessageChannelToInputFluxParameterAdapter.java:67) ~[spring-cloud-stream-reactive-1.2.2.RELEASE.jar:1.2.2.RELEASE]
```
That is what must be fixed on Spring Cloud Stream side: https://github.com/spring-cloud/spring-cloud-stream

I see they have already `2.0` branch against Spring Boot 2.0, but their Reactor version is still `3.0.5`.

/CC @mbogoevici , @sobychacko

@noorulhaq ,

Thank you for your all effort to bring these monsters to the scene together, but looks like you are stuck with SI-5.0 M3 for now. Until there will be proper SCSt 2.0 build with an appropriate Reactor dependency.

**Comment by noorulhaq** [comment]
Hi,

I have one more suggestion. As having the facility of mixing both JavaDSL and Reactor seems a very powerful option, I see it as a risk also at the same time, because of the same mistakes I have been doing in my sample code above. An API user has to be very careful about when he/she might jump out of the reactive paradigm. 

So my suggestion is to document this concern more explicitly for the API users, in the same way, how spring documents for rest of the projects.

**Comment by artembilan** [comment]
Please, raise a JIRA on the matter with more concrete description and particular samples.

Thanks
