### ISSUE TITLE
Expose setters from AbstractRemoteFileOutboundGateway in FTP.outboundGateway

### ISSUE THREAD

**Issue by psoares** [spring-projects/spring-integration-java-dsl#151]
Hi,
I was trying to find a way to resume FTP downloads when using `FTP.outboundGateway` in the DSL syntax.

The only way I could make this work was by declaring separate bean, as follows :
```java
@Bean
public AbstractRemoteFileOutboundGateway<FTPFile> ftpMgetSpec() {
   AbstractRemoteFileOutboundGateway<FTPFile> gateway = Ftp.outboundGateway(
           ftpSessionFactory(),
           AbstractRemoteFileOutboundGateway.Command.MGET,
           "payload.concat('/*')"
    )
            .localDirectory("/tmp/downloads").options(
                    AbstractRemoteFileOutboundGateway.Option.STREAM,
                    AbstractRemoteFileOutboundGateway.Option.PRESERVE_TIMESTAMP)
            .get();

    gateway.setFileExistsMode(FileExistsMode.APPEND);

    return gateway;
}

@Bean
public IntegrationFlow downloadExample() {
    return IntegrationFlows.from("someChannel")
                .handle(ftpMgetSpec())
                .log()
                .get();
}
```

It would be nice to expose the setters of `AbstractRemoteFileOutboundGateway` at the Spec level so we could configure properties like `setFileExistsMode` inline in the DSL.

**Comment by artembilan** [comment]
This has been fixed via https://github.com/spring-projects/spring-integration-java-dsl/commit/2e20ca86b6330de65501b2c422769cf0aeddf1cc.

There no too much problems to release `1.2.3`, plus you have already a workaround.

Currently Java DSL has been moved to the Spring Integration `5.0`, which is going to be released in October/November. That is if you worry about an upgrade.

If we release `1.2.3`, I'll let you know.

Thank you for interest in the project!

**Comment by psoares** [comment]
Great to hear. Thank you!
