### ISSUE TITLE
FileInboundChannelAdapterSpec external scanner

### ISSUE THREAD

**Issue by maellg** [spring-projects/spring-integration-java-dsl#152]
Hi,
I'm trying to use a HeadDirectoryScanner and I'm struggling with the DSL. Here's the code I have: 

```java
DirectoryScanner directoryScanner = new HeadDirectoryScanner(maxMessagesPerPoll);
directoryScanner.setLocker(new NioFileLocker());
directoryScanner.setFilter(new RegexPatternFileListFilter(patternFilter));
return IntegrationFlows
        .from(s -> s.file(Paths.get(directory).toFile())
                        .scanEachPoll(true)
                        .scanner(directoryScanner),
                e -> e.poller(Pollers.fixedDelay(delay, TimeUnit.SECONDS).maxMessagesPerPoll(maxMessagesPerPoll))
        )
        .channel("inboundFileChannel")
        .get();
```

And here is the exception message I get:

```The 'filter' and 'locker' options must be present on the provided external 'scanner': org.springframework.integration.file.HeadDirectoryScanner@7d528cf7```

From my understanding, this exception is supposed to force you to set the locker and the filter directly on the Scanner instead of setting it on FileReadingMessageSource. Which is actually what I'm doing so I took a look at the code and noticed that a filter is systematically set on FileInboundChannelAdapterSpec ([line 60 of the current code](https://github.com/spring-projects/spring-integration-java-dsl/blob/master/src/main/java/org/springframework/integration/dsl/file/FileInboundChannelAdapterSpec.java#L60)). So I guess it's the reason for the exception I get? 
Am I doing something wrong or doesn't the code allow the use of an external scanner?

Thanks.

**Comment by artembilan** [comment]
No, you're doing correct. That is really a bug.

As a workaround you should declare `FileReadingMessageSource` manually and use it from the DSL:
```
private FileReadingMessageSource fileReadingMessageSource() {
	DirectoryScanner directoryScanner = new HeadDirectoryScanner(maxMessagesPerPoll);
	directoryScanner.setLocker(new NioFileLocker());
	directoryScanner.setFilter(new RegexPatternFileListFilter(patternFilter));
			
	FileReadingMessageSource fileReadingMessageSource = new FileReadingMessageSource();
	fileReadingMessageSource.setDirectory(Paths.get(directory).toFile());
	fileReadingMessageSource.setScanEachPoll(true);
	return fileReadingMessageSource;
}
```
And use it like:
```
return IntegrationFlows
        .from(fileReadingMessageSource(),
                e -> e.poller(Pollers.fixedDelay(delay, TimeUnit.SECONDS).maxMessagesPerPoll(maxMessagesPerPoll))
)
```

**Comment by maellg** [comment]
@artembilan: Ok, thanks for the quick reply and the workaround.
