### ISSUE TITLE
Unhelpful micrometer "name" tag for integration components

### ISSUE THREAD

**Issue by mrusinak** [spring-projects/spring-integration-java-dsl#156]
The meters created for spring-integration components are not helpful, as the tag "name" used to distinguish which component the metric is for is based on a bean name the user has little to no control over.

Since the actual user components are not tied to metrics (the handlers that wrap them are - for example, a ObjectToJsonTransformer has no metrics, but the generated MessageTransformerHandler that wraps it is), it becomes pretty impossible to try and affect the value used for "name" tag of a metric. For example, consider an outbound flow:

    return IntegrationFlows
            .from(channel)
            .transform(new ObjectToJsonTransformer())
            .transform(new EncryptionTransformer())
            .headerFilter(JsonHeaders.TYPE_ID)
            .handle(Kafka.outboundChannelAdapter(factory).topic(topic))
            .get();

This will produce meters in the ```MeterRegistry``` that look like the following:

    [
      {
        "name": "spring.integration.send",
        "tags": {
          "exception": "none",
          "name": "org.springframework.integration.transformer.MessageTransformingHandler#4",
          "result": "success",
          "type": "handler"
        }
      },
      {
        "name": "spring.integration.send",
        "tags": {
          "exception": "none",
          "name": "org.springframework.integration.transformer.MessageTransformingHandler#5",
          "result": "success",
          "type": "handler"
        }
      },
      ....
    ]

Having multiple flows (even in the simple case of inbound/outbound, let alone different logical channels) quickly makes whatever these metrics are tracking useless.

The most success I had with fixing this in my code was iterating through a ```StandardIntegrationFlow``` 's components **before** it was returned as a bean, needing to go through several layers to eventually ```setComponentName``` on the handlers. It proved impossible to do this after the bean was created (but before metrics were bound) due to ```ConsumerEndpointFactoryBean``` having no paths to get to the eventual transformer/filter being used.

At the most basic, I would like be able to have the metric names include the name of the integration flow they belong to, along with the component-type of the filter/transformer. Off hand I don't have a suggestion on a good approach to handle metric naming mechanism that covers lambdas or multiple steps of the same type in the same flow.

**Comment by artembilan** [comment]
What version of Spring Integration do you use?
I assume something like > `5.0`. The Micrometer support has been introduced since there.
This project is in attic  and is not compatible with Spring Integration `5.0`: https://github.com/spring-projects/spring-integration-java-dsl/wiki/Spring-Integration-Java-DSL-Reference

If that is the case, please, consider to close this issue and move it into the Spring Integration JIRA: https://jira.spring.io/projects/INT

Will will try to help you from there.

Thanks for understanding.

**Comment by mrusinak** [comment]
Correct, I was using Spring > 5.0 - I forgot this project was consolidated into with that release. Apologies, and thanks! I will move the ticket
