### ISSUE TITLE
What is the equivalent of "chain" in java DSL?

### ISSUE THREAD

**Issue by vincentmonier** [spring-projects/spring-integration-java-dsl#26]
Hi,

I was trying to convert the following xml based definition for a chain of service activators

`<int:chain id="chainId" input-channel="inputChannel" output-channel=">`
`     <int:service-activator ref="service1" method="method1" />`
`      <int:service-activator ref="service2" method="method2" />`
`      <int:service-activator ref="service3" method="method3" />`
`</int:chain>`

but I cannot see any support for chain, or does another mechanism exist?

Thanks for your answer.

**Comment by artembilan** [comment]
Hi @vincentmonier !

Thank you for feedback.
Can you tell us why this isn't similar what you are looking for?
````java
@Bean                                           
public IntegrationFlow chainFlow() {            
	return IntegrationFlows.from("inputChannel")
			.handle("service1", "method1")      
			.handle("service2", "method2")      
			.handle("service3", "method3")      
			.channel("outputChannel")           
			.get();                             
}                                               
````

**Comment by vincentmonier** [comment]
Yep it works, the problem was in my test.

Sorry and thank you for your answer.

**Comment by artembilan** [comment]
No problem!
Any reasonable feedback is always welcome.
There is a `MessageHandlerChain`, of course, to use it as a single `.handle()`, but that requires more work to populate `MethodInvokingMessageHandler`s for each of your services and inject to the first.
The DSL does that for you on the background, however it doesn't use `MessageHandlerChain` there.
And all those `.handle()` populate `EventDrivenConsumer` as well.
