### ISSUE TITLE
What is the equivalent of logging-channel-adapter in java DSL

### ISSUE THREAD

**Issue by vincentmonier** [spring-projects/spring-integration-java-dsl#28]
Hi,

I was not able to find a simple translation of the following XML configuration in a full Java DSL.

I define a MessageChannel bean with a WireTap interceptor (I use version 1.0.1 which does not have WireTapSpec):

```java
@Bean
public MessageChannel myChannel(MessageChannel myLogChannel) {
return MessageChannels.direct()
                .interceptor(new WireTap(myLog))
                .get();
}
```
The problem is that I have to keep `myLog` channel adapter definition in XML because I was not able to find an equivalent declaration
```xml
 <int:logging-channel-adapter id="myLog" channel="myLogChannel"  logger-name="name" />
```
I assume there's a better way to achieve this.

**Comment by artembilan** [comment]
Hi again!

Right, the `.wireTap()` will be available since `1.1` version.
Your configuration for the `myChannel` looks good. 
And now you just should to specify `<int:logging-channel-adapter>` with DSL, or even just with simple JavaConfig:
````java
@Bean IntegrationFlow logFlow() {
     LoggingHandler loggingHandler =  new LoggingHandler(LoggingHandler.Level.INFO.name());
     loggingHandler.setLoggerName(name);
     return IntegrationFlows.from("myLogChannel")
                           .handle(loggingHandler)
                           .get();
}
````
Or just as generic one:
````java
@Bean
@ServiceActivator(inputChannel = "myLogChannel")
public MessageHandler logger() {
     LoggingHandler loggingHandler =  new LoggingHandler(LoggingHandler.Level.INFO.name());
     loggingHandler.setLoggerName(name);
     return loggingHandler;
}
````

**Comment by vincentmonier** [comment]
Ok not as simple as I was expected but hey..

**Comment by artembilan** [comment]
I found another way to code more smoothly for your case:
````java
.handle(new LoggingHandler(LoggingHandler.Level.DEBUG.name()),
							e -> e.get().getT2().setLoggerName("foo"))
````
To be honest we aren't seeking a coverage with Builders for all `MessageHandler` implementations.
And maybe it even would be better to separate `@Bean` definitions for those out-of-the-box handlers and use their reference from the DSL:
````java
@Bean
public MessageHandler logger() {
     LoggingHandler loggingHandler =  new LoggingHandler(LoggingHandler.Level.INFO.name());
     loggingHandler.setLoggerName(name);
     return loggingHandler;
}

@Bean IntegrationFlow logFlow() {
     return IntegrationFlows.from("myLogChannel")
                           .handle(logger())
                           .get();
}
````

By the way, we've just released `1.1.0.M1`, so you can try to use built-in `.wireTap()` ability:
````java
@Bean IntegrationFlow logFlow() {
     return IntegrationFlows.from("input")
                           .handle(...)
                           .wireTap(f -> f.handle(logger()))
                           .transform(...)
                           .get();
}
````

**Comment by artembilan** [comment]
@vincentmonier , do have else any concerns to this issue?
Can we close it?
Thanks

**Comment by vincentmonier** [comment]
Yes thank you it was useful
