### ISSUE TITLE
How to use an annotated transformer with Java DSL

### ISSUE THREAD

**Issue by vincentmonier** [spring-projects/spring-integration-java-dsl#29]
Hi another newbie question, 

In XML based definition I used to define transformer like this:
```xml
<int:transformer ref="transformerBean" />
```
with the Bean:

```java
public class TransformerBean

@Transformer
public Object myMethod(Object payload) {
...
}
```

Since my bean is not a `GenericTransformer` the only way I found so far is:
```java
IntegrationFlows.from("inputChannel")
                .transform("@transformerBean.myMethod(payload)")
                .channel("outputChannel")
                .get();
```
I'm sure there's a more elegant way to achieve this configuration.

Thanks

**Comment by artembilan** [comment]
Yeah... That's true. 
We have introduced many helpful EIP-methods since `1.1` like:
````java
.transform(myTransformerBean)
.transform(myTransformerBean, "myMethod")
````
Of course, you can wrap your POJO to the `GenericTransformer`:
````java
.transform(p -> myTransformerBean.myMethod(p))
````

**Comment by artembilan** [comment]
Well, Having `1.1.0.M1` release you can do like this already:
````java
.transform(myTransformerBean)
````
where your `@Transformer` method will be determined by Framework automatically.

**Comment by artembilan** [comment]
@vincentmonier , do have else any concerns to this issue?
Can we close it?
Thanks
