### ISSUE TITLE
Amqp Inbound Channel does not acknowledge messages (RabbitMQ)

### ISSUE THREAD

**Issue by vincentmonier** [spring-projects/spring-integration-java-dsl#33]
Hi,

don't know if it's a problem with my configuration or a really issue on class. *AmqpInboundChannelAdapterSpec*

I have the following flow configuration:
```java
@Bean
public IntegrationFlow backofficeMessageInputFlow() {
       return IntegrationFlows.from(Amqp.inboundAdapter(connectionFactory, inputQueue)
                .concurrentConsumers(10)
                .prefetchCount(prefetchCount)
                .errorChannel(errorChannel)
                .id("messageAmqpInbound"))
                .gateway(fromInputQueue())
                .get();
}
```
I send 10 messages to my RabbitMQ queue. They are dequeued but none of them are acknowledged. 
If i use the following XML based configuration everything works fine:
```xml
<int-amqp:inbound-channel-adapter id="messageAmqpInbound"
		channel="fromInputQueue" 
		queue-names="inputQueue" 
		error-channel="errorChannel" 
		connection-factory="connectionFactory"
		concurrent-consumers="10"
		prefetch-count="1" />
```
According to Spring integration documentation *acknowledge-mode* is *AUTO* when using namespace definition, is it the same for *AmqpInboundChannelAdapterSpec*

**Comment by artembilan** [comment]
It is `AUTO` by default on the `org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer`. So, it's far away from DSL, too.

Looks like you have an issue with that `.gateway(fromInputQueue())`. Gateway is two-way (request-reply) component and it isn't enough just send message to the `fromInputQueue` within gateway.
Why it isn't enough for you just use it like `.channel(fromInputQueue())` ?

And I am meanwhile testing `Amqp.inboundAdapter`...

**Comment by artembilan** [comment]
Well, we have test with that and looks like it works well.

**Comment by vincentmonier** [comment]
I changed gateway to channel, but still have the problem...

**Comment by vincentmonier** [comment]
I changed gateway to channel it works perfectly. 

Thanks.

**Comment by vincentmonier** [comment]
I changed gateway to channel it works perfectly.
Thanks.
