### ISSUE TITLE
Transformers.xslt could be annotated with SafeVarargs

### ISSUE THREAD

**Issue by codingtim** [spring-projects/spring-integration-java-dsl#37]
Hi, 

I was using `org.springframework.integration.dsl.support.Transformers.xslt(Resource xsltTemplate, Tuple2<String, Expression>... xslParameterMappings)` today and I noticed that it gives a compiler warning. I think this could be fixed if a `@SafeVarargs` annotation was added to this method.

Kind regards.

**Comment by artembilan** [comment]
Thank you for pointing this out!
This is fixed with #31.
This will work even with Java 6, because it compiler is already familiar with non-existing annotation ignoring.
No need to backport it because it is just a `warn`and can be suppressed on the user side.
