### ISSUE TITLE
IntegrationFlow.handle does not invoke advisor list

### ISSUE THREAD

**Issue by t4gedieb** [spring-projects/spring-integration-java-dsl#49]
Advisors added to fully initialized AbstractReplyProducingMessageHandler by the application context won't be invoked.
Lambda expression MessageHandler, which are created on the fly, work fine, as they were not yet initialized, but MessageHandler defined in the application context, which are already full initialized will ignore the advisor list as the required method onInit() won't be invoked again.

        @Bean
        public IntegrationFlow handleMessageHandlerWithAdvice() {
            return f -> f
                    .handle(messageHandler(),
                            spec -> spec
                                    .advice(delayedAdvice()));
        }

To illustrate the problem I created a little test case.
1. Flow with Lambda expression --> works as expected
2. Flow with MessageHandler defined in the application context --> will ignore advisor list
I hope I could explain the problem well enough and let me know if you need more information.

As a workaround I can set the advisor list directly on the AbstractReplyProducingMessageHandler. The question is this the expected behavior and design or is this a bug?

	package org.springframework.integration.dsl.test.flows;

	import static java.lang.Boolean.FALSE;
	import static java.lang.Boolean.TRUE;
	import static org.hamcrest.Matchers.is;
	import static org.junit.Assert.assertThat;
	import static org.springframework.integration.dsl.channel.MessageChannels.queue;
	import static org.springframework.integration.test.matcher.PayloadMatcher.hasPayload;
	import static org.springframework.messaging.MessageHeaders.REPLY_CHANNEL;
	import static org.springframework.messaging.support.MessageBuilder.withPayload;

	import org.junit.Test;
	import org.junit.runner.RunWith;
	import org.springframework.beans.factory.annotation.Autowired;
	import org.springframework.beans.factory.annotation.Qualifier;
	import org.springframework.context.annotation.Bean;
	import org.springframework.context.annotation.Configuration;
	import org.springframework.integration.channel.QueueChannel;
	import org.springframework.integration.config.EnableIntegration;
	import org.springframework.integration.dsl.IntegrationFlow;
	import org.springframework.integration.dsl.test.flows.IntegrationFlowTests.DelayedAdvice;
	import org.springframework.integration.handler.AbstractReplyProducingMessageHandler;
	import org.springframework.messaging.Message;
	import org.springframework.messaging.MessageChannel;
	import org.springframework.test.annotation.DirtiesContext;
	import org.springframework.test.context.ContextConfiguration;
	import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
	import org.springframework.test.context.support.AnnotationConfigContextLoader;

	/**
	 * @author Michael Wirth
	 *
	 */

	@ContextConfiguration(loader = AnnotationConfigContextLoader.class)
	@RunWith(SpringJUnit4ClassRunner.class)
	@DirtiesContext
	public class IntegrationFlowWithAdviceTest {

		@Configuration
		@EnableIntegration
		public static class ContextConfiguration {
			@Bean
			public DelayedAdvice delayedAdvice() {
				return new DelayedAdvice();
			};

			@Bean
			public AbstractReplyProducingMessageHandler messageHandler() {

				return new AbstractReplyProducingMessageHandler() {

					@Override
					protected Object handleRequestMessage(Message<?> requestMessage) {
						return "RESPONSE";
					}

				};
			}

			@Bean
			public IntegrationFlow handleLambdaWithAdvice() {
				return f -> f
						.handle((p, h) -> "RESPONSE",
								spec -> spec
										.advice(delayedAdvice()));
			}

			@Bean
			public IntegrationFlow handleMessageHandlerWithAdvice() {
				return f -> f
						.handle(messageHandler(),
								spec -> spec
										.advice(delayedAdvice()));
			}

		}

		@Autowired
		private DelayedAdvice delayedAdvice;

		@Autowired
		@Qualifier("handleLambdaWithAdvice.input")
		private MessageChannel handleLambdaWithAdviceInput;

		@Autowired
		@Qualifier("handleMessageHandlerWithAdvice.input")
		private MessageChannel handleMessageHandlerWithAdviceInput;

		/**
		 * Test advisor is added and invoked to a {@code AbstractReplyProducingMessageHandler} defined and initialized by the {@code IntegrationFlow}.
		 * 
		 * If the {@code MessageHandler} is defined and initialized by the {@code IntegrationFlow} the adisors work as expected.
		 * The {@code ConsumerEndpointSpec} adds the advisorList to an on the fly created {@code ServiceActivator}.
		 * The initialization of this {@code AbstractReplyProducingMessageHandler} is taking place after the registration {@code IntegrationFlow.handle} and will init the MessageHandler with the required
		 * advisor proxy.
		 */
		@Test
		public void testHandleLambdaWithAdvice() {

			assertThat(delayedAdvice.getInvoked(), is(FALSE));

			QueueChannel replyChannel = queue().get();
			Message<?> message = withPayload("REQUEST")
					.setHeader(REPLY_CHANNEL, replyChannel)
					.build();

			handleLambdaWithAdviceInput.send(message);
			Message<?> receive = replyChannel.receive(5000);

			assertThat(receive, hasPayload("RESPONSE"));
			assertThat(delayedAdvice.getInvoked(), is(TRUE));
		}

		/**
		 * Test advisor is added and invoked to a {@code AbstractReplyProducingMessageHandler} defined in the application context.
		 * 
		 * If the MessageHandler is defined and initialized in the application context the advisors won't work.
		 * The AbstractReplyProducingMessageHandler adds the advisor in it's {@code AbstractReplyProducingMessageHandler.onInit} method in the initialization phase.
		 * 
		 * The {@code ConsumerEndpointSpec} adds the advisorList to an already full initialized {@code MessageHandler}, which won't have any effect anymore and the advisor won't be invoked.
		 */
		@Test
		public void testHandleMessageHandlerWithAdvice() {

			assertThat(delayedAdvice.getInvoked(), is(FALSE));

			QueueChannel replyChannel = queue().get();
			Message<?> message = withPayload("REQUEST")
					.setHeader(REPLY_CHANNEL, replyChannel)
					.build();

			handleMessageHandlerWithAdviceInput.send(message);
			Message<?> receive = replyChannel.receive(5000);

			assertThat(receive, hasPayload("RESPONSE"));
			assertThat(delayedAdvice.getInvoked(), is(TRUE));
		}
	}

**Comment by artembilan** [comment]
Hi @t4gedieb !

Thank you for pointing this out. 
Indeed, even if we have this code:
````java
if (messageHandler instanceof AbstractReplyProducingMessageHandler) {
	((AbstractReplyProducingMessageHandler) messageHandler).setAdviceChain(this.adviceChain);
}
````
in the `ConsumerEndpointSpec` ctor, it does not make affect anymore because your `MessageHandler` is initialized by the applicationContext before that `IntegrationFlow` "population" process.

You have two options to fix it:
1. Just remove `@Bean` on the `messageHandler()` and the Spring Integration Java DSL will take care about bean initialization for you.
2. As you mentioned above: move the `AbstractReplyProducingMessageHandler` option definitions to the particular bean definition and don't use the `.advice()` configuration from the `IntegrationFlow`.

I'm not sure if we will be able to fix it somehow, because we don't have any state in the `AbstractReplyProducingMessageHandler` to deal with in between its `.afterPropertiesSet()` and that `.setAdviceChain(this.adviceChain)`.

We can add some `INFO` message, though, to warn end-users that external beans aren't affected by the DSL configuration.

By the way the same issue (or expected behavior) we have even with the raw Spring Configuration not just this DSL style:

````java
private class Foo {

	private String foo;

	private String FOO;

	@PostConstruct
	public void init() {
		this.FOO = foo.toUpperCase();
	}

	public void setFoo(String foo) {
		this.foo = foo;
	}

	public String getFoo() {
		return this.foo;
	}

	public String getFOO() {
		return this.FOO;
	}

}
````

````java
@Bean
public Foo foo() {
	Foo foo = new Foo();
	foo.setFoo("foo");
	return foo;
}

@Bean
public String bar() {
	foo().setFoo("bar");
	return "bar";
}
````
````java
@Autowired
private Foo foo;

@Test
public void testFoo() {
	assertEquals("bar", foo.getFoo());
	assertEquals("FOO", foo.getFOO());
}
````

Let me know what you think on the matter, because I'm afraid we are forced to close it as `Work as Designed` :smile: .

**Comment by t4gedieb** [comment]
Hi artembilan, 

Thanks for the feedback. 
I think an info message and an entry in the documentation would be helpful, as I was looking into the problem quiet a while to figure out if there is a bug in my configuration or if it's a bug in the framework. From my point-of-view it's ok to close the issue as it `Work as Designed`. :thumbsup:
