### ISSUE TITLE
Jms Message Driven Channel Adapter Typo

### ISSUE THREAD

**Issue by magiccrafter** [spring-projects/spring-integration-java-dsl#55]
The following 3 methods may be renamed:
Current/From: Jms.messageDrive**r**ChannelAdapter(...)
To: Jms.messageDrive**n**ChannelAdapter(...)

This is really a tiny typo of the method signature that would be a breaking change when updating. I just decided to share it because I use the spring-integration-java-dsl in my projects and I like it :)

Thanks for the amazing work!

**Comment by artembilan** [comment]
Hi @magiccrafter !

Thank you for catching that out!

As you see it is fixed already. We found the good compromise in face of `@Deprecated` :smile:
