### ISSUE TITLE
Add Splitters factory

### ISSUE THREAD

**Issue by kennyk65** [spring-projects/spring-integration-java-dsl#63]
I'm new to the DSL, and I've found that where factories exist (like Transformers, Pollers, MessageChannels, Amqp, Jms, Files, Ftp, Mail, etc,) it is pretty easy to learn what options are available.  Recently I went to do an Xpath Splitter and was stuck for a while as I could not figure out what class to use to implement it.  Turns out it was easy to implement, but difficult to discover.

Suggest creating a Splitters factory in the spirit of the other existing factories.

**Comment by englishman** [comment]
@artembilan 

1. Could you, please, tell me what you wanna be implemented here?
2. Should it be implemented here org.springframework.integration.dsl.*splitter*?

**Comment by artembilan** [comment]
The external discussion on the matter: http://stackoverflow.com/questions/36145116/spring-integration-dsl-how-to-create-an-xpath-splitter/36145193.

@englishman , thank you for your attention to this one!
Please, see issue description.

We should introduce `org.springframework.integration.dsl.support.Splitters` factory alongside with the existing `Transformers` to all know `AbstractMessageSplitter` implementations in the Spring Integration. One of them is `XPathMessageSplitter`, another sample is `FileSplitter`.

Such a Factory should help end-users to define beans and `IntegrationFlow`s with more smooth manner.

See more information about the framework in the [Reference Manual](https://github.com/spring-projects/spring-integration-java-dsl/wiki/Spring-Integration-Java-DSL-Reference).

Plus for case to spread the world a bit I'm duplicating the note from the [Spring Integration Core Manual](http://docs.spring.io/spring-integration/docs/4.3.0.BUILD-SNAPSHOT/reference/html/overview.html#programming-tips) here, too:

> If you are familiar with Spring Integration XML configuration already, starting with version 4.3, we provide in the XSD elements definitions the description with the pointer which target classes are used to produce beans for the adapter or gateway, for example:

> ````xml
<xsd:element name="outbound-async-gateway">
    <xsd:annotation>
		<xsd:documentation>
Configures a Consumer Endpoint for the 'o.s.i.amqp.outbound.AsyncAmqpOutboundGateway'
that will publish an AMQP Message to the provided Exchange and expect a reply Message.
The sending thread returns immediately; the reply is sent asynchronously; uses 'AsyncRabbitTemplate.sendAndReceive()'.
      </xsd:documentation>
</xsd:annotation>
````

**Comment by artembilan** [comment]
Having only two target protocols `AbstractMessageSplitter` implementation as `FileSplitter` and `XPathMessageSplitter` it doesn't make much sense to introduce that new `Splitters` factory.

It looks much better to have `XML` factory for all components in SI-xml module.

The `FileSplitter` is covered already via `Files.splitter()` factory methods.
