### ISSUE TITLE
Make message routing parameterized 

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration-java-dsl#68]
At this moment it isn't possible to use type strict expressions for message routing. Currently only strings are allowable as individual router key. 

**Example 1:**
```java
...
.route("payload.eventType", m -> m
    .subFlowMapping(EventType.NEWM.name(), sf -> sf.transform(...))
    .subFlowMapping(EventType.CANC.name(), sf -> sf.transform(...))
)
...
```
I would expect `Enum` usage without conversion to `String` here.

**Example 2**
`PayloadTypeRouter` EIP isn't type safe too
```java
@Bean
public IntegrationFlow processorChain() {
    return IntegrationFlows.from(systemInputChannel())
            .<Object, String>route(p -> p.getClass().getName(), // transform raw payload to mapping string key
                            .channelMapping(String.class.getTypeName(), "stringConsumerChannel")
                            .channelMapping(BusinessModel.class.getTypeName(), "businessConsumerChannel")
                            .channelMapping(ArrayList.class.getTypeName(), "listConsumerChannel")
            )
            .get();
}
```

**Comment by artembilan** [comment]
Hello @englishman !

Thank you for raising the issue, but you mind to provide more background?

Right it isn't clear what we should to improve.
The `PayloadTypeRouter` is a part of Spring Integration Core project. So, maybe the concern should be considered there...

**Comment by englishman** [comment]
@artembilan added description and examples

**Comment by artembilan** [comment]
H-m-m. Interesting...

This won't be possible until the `AbstractMappingMessageRouter` doesn't start support `Object` for the channel key. Its logic is fully based on the `MappingMessageRouterManagement` which is designed for the JMX...

Although... We may really can find some hook with the `RouterSpec.RouterSubFlowMappingProvider`, when can borrow the conversion logic:
```
		else if (this.getRequiredConversionService().canConvert(channelKey.getClass(), String.class)) {
				addChannelFromString(channels, this.getConversionService().convert(channelKey, String.class), message);
			}
			else {
				throw new MessagingException("unsupported return type for router [" + channelKey.getClass() + "]");
			}
```

@garyrussell , WDYT?

@englishman , your thoughts? How would you like to achieve that?

**Comment by artembilan** [comment]
See also some related Spring Integration [JIRA](https://jira.spring.io/browse/INT-4057).
