### ISSUE TITLE
`FileInboundChannelAdapterSpec` Filtering Not Fluent

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-integration-java-dsl#72]
By "not fluent" I mean that one cannot expect a particular behavior from the methods available - it produces unintuitive results. When one creates a `FileInboundChannelAdapterSpec`, it produces a default configuration that will ignore duplicates and hidden fields. If you then call `ignoreDuplicates()`, the behavior is that it no longer ignores hidden fields! Also there is no way to make it allow duplicates other than by completely replacing its `DirectoryScanner`, or by providing a list of filters that do not contain an `AcceptOnce` filter. The deprecated `preventDuplicatesFilter()` does not work correctly either. The reason this is all the case is because the default `DirectoryScanner` already has a set of filters.

I suggest a fix would be to have the `FileInboundChannelAdapterSpec` default to an empty filter list that it always sets on the target object. Then methods like `ignoreDuplicates()` will make sense in that they add ignoring of duplicates and do not take away other filters.

**Comment by artembilan** [comment]
Thank you for pointing that out!

Not sure why the logic (my fault, of course :wink: ) in the `FileInboundChannelAdapterSpec` isn't just linear like it is in the `FileInboundChannelAdapterParser`. That just ends up with the result from the `FileListFilterFactoryBean`.

So, let me come here for the `FileInboundChannelAdapterParser` with the the same `FileListFilterFactoryBean` foundation and we'll see in the PR where we are and where to go!

**Comment by artembilan** [comment]
See the PR #73 .

Now everything is based on the `FileListFilterFactoryBean`, like it is done in the SI File module.
Even if we override the default setting in the `DefaultDirectoryScanner` like you pointed above, the `IgnoreHiddenFileListFilter` is still there, because of the `FileListFilterFactoryBean` logic like:
````java
if (!Boolean.FALSE.equals(this.ignoreHidden)) {
	filtersNeeded.add(new IgnoreHiddenFileListFilter());
}
if (this.filter != null) {
	if (Boolean.TRUE.equals(this.preventDuplicates)) {
		filtersNeeded.add(new AcceptOnceFileListFilter<File>());
		filtersNeeded.add(this.filter);
	}
	else { // preventDuplicates is either FALSE or NULL
		filtersNeeded.add(this.filter);
	}
}
else if (this.filenamePattern != null || this.filenameRegex != null) {
	if (!Boolean.FALSE.equals(this.preventDuplicates)) {
		filtersNeeded.add(new AcceptOnceFileListFilter<File>());
	}
	if (this.filenamePattern != null) {
		filtersNeeded.add(new SimplePatternFileListFilter(this.filenamePattern));
	}
	if (this.filenameRegex != null) {
		filtersNeeded.add(new RegexPatternFileListFilter(this.filenameRegex));
	}
}
else if (Boolean.FALSE.equals(this.preventDuplicates)) {
	filtersNeeded.add(new AcceptAllFileListFilter<File>());
}
else { // preventDuplicates is either TRUE or NULL
	filtersNeeded.add(new AcceptOnceFileListFilter<File>());
}
````

Right now we fully delegate from the `FileInboundChannelAdapterSpec` to the `FileListFilterFactoryBean`, so any expected combinations should be fine.

Feel free to share any feedback!

**Comment by SingleShot** [comment]
Looks good. Thanks!
