### ISSUE TITLE
Add support to scatter-gather pattern

### ISSUE THREAD

**Issue by lgbanuelos** [spring-projects/spring-integration-java-dsl#75]
The scatter-gather is a frequently used enterprise integration pattern (EIS). The Spring Integration provides support to this pattern from version 4.1. The same pattern can be implemented by a combination of a splitter/publish-subscribe and aggregator. IMO adding support to this pattern in Java DSL would improve readability of the code (because it reflects the intention) and would result in more succinct flow specifications (in this moment, the flow must be split into two parts -- a scatter-gather construct would allow to keep the parts together).

An example of this pattern, implemented with separate flows is given at http://stackoverflow.com/questions/36742888/spring-integration-java-dsl-configuration-of-aggregator

**Comment by artembilan** [comment]
Excelent, @lgbanuelos !

We even won't mind a [Contribution](https://github.com/spring-projects/spring-integration-extensions/wiki/Contributor-Guidelines) :smile: 

Thank you and looking forward for more feedback!
