### ISSUE TITLE
InboundGateway request channel overwritten

### ISSUE THREAD

**Issue by damienhollis** [spring-projects/spring-integration-java-dsl#81]
Hi,

We are trying to configure a specific requestChannel on a inboundGateway as follows.
`Jms.inboundGateway(container).requestChannel(requestChannel).get()`

And then configuring a message flow from that gateway:
`IntegrationFlows.from(olapInboundGateway())...`

However, the code that creates the integration flow, looks like this:
```	
public static IntegrationFlowBuilder from(MessagingGatewaySupport inboundGateway) {
	DirectFieldAccessor dfa = new DirectFieldAccessor(inboundGateway);
	MessageChannel outputChannel = (MessageChannel) dfa.getPropertyValue("requestChannel");
	if (outputChannel == null) {
		outputChannel = new DirectChannel();
		inboundGateway.setRequestChannel(outputChannel);
	}
	return from(outputChannel).addComponent(inboundGateway);
}
```

The problem is that getPropertyValue is reading the requestChannel from the inboundGateway but the requestChannel is actually set on the GatewayDelegate, as a result of the JmsInboundGateway implementation:

```
@Override
public void setRequestChannel(MessageChannel requestChannel) {
	this.listener.setRequestChannel(requestChannel);
}
```

So the requestChannel is always null when it is read and then the channel we have configured is overwritten by setRequestChannel.

Cheers,
Damien

**Comment by artembilan** [comment]
This is a bug and will be fixed today with backport into `1.1.x`.

Meanwhile there is a workaround for you.
You don't need to specify that `requestChannel()` on the `Jms.inboundGateway()` definition and you can just rely on the `.channel()` semantics during `IntegrationFlow` configuration. Something like this:
````java
IntegrationFlows.from(Jms.inboundGateway(container))
                    .channel(requestChannel)
            ...
````
That `.channel(requestChannel)` is translated exactly into that `requestChannel` of the `MessagingGatewaySupport`.

You can still declare `Jms.inboundGateway()` in the separate method, but yes, without `requestChannel` it can't be as a `@Bean`.

See https://github.com/spring-projects/spring-integration-java-dsl/wiki/Spring-Integration-Java-DSL-Reference for gateways and channel definitions.

**Comment by artembilan** [comment]
The same problem is with `JmsMessageDrivenChannelAdapter`.

**Comment by damienhollis** [comment]
Thanks for the feedback.  

I actually tried your workaround yesterday but it resulting in no messages being processed.  I didn't do much investigation as I just assumed I was using the channel incorrectly.  If I have time today, I'll try that workaround again.
