### ISSUE TITLE
Use of transform() in DSL when method in transform bean has @Header annotation

### ISSUE THREAD

**Issue by iainporter** [spring-projects/spring-integration-java-dsl#90]
I would like to use the following syntax:
```
.transform(myTransformBean)
```
but have to resort to this:
```
.handle((p,h) -> myTransformBean.transform((String)p, (Long)h.get("myID")))
```
my transform bean has the following method:
```
@Transformer
public MyPOJO transform(String rawData, @Header("myID") Long id)
```
Due to the header param I can't extend `GenericTransformer`

At the moment the `@Header` and `@Transformer` annotations are redundant

**Comment by artembilan** [comment]
You don't need to extend `GenericTransformer`. 
There is EIP-method like:
```
/**
 * Populate the {@code MessageTransformingHandler} for the {@link MethodInvokingTransformer}
 * to invoke the discovered service method at runtime.
 * @param service the service to use.
 * @return the current {@link IntegrationFlowDefinition}.
 * @see ExpressionEvaluatingTransformer
 * @since 1.1
 */
public B transform(Object service) {
	return transform(service, null);
}
```

Please, be more specific. Right now your question isn't clear.

**Comment by iainporter** [comment]
I want my transform bean to be discovered at runtime.
I don't care so much about extending GenericTransform

the main point of my issue was that I want to annotate my method with @Header and not have to then pass that in as an argument

i.e. i want this:

.transform(myTransformBean)

instead of this:

..handle((p,h) -> myTransformBean.transform((String)p, (Long)h.get("myID")))

**Comment by artembilan** [comment]
And? What doesn't work? Sorry, you almost copy/paste your original question...
I show you a method which meets your requirements and works exactly like you are asking. The test case in the project demonstrate that:

```
@Component
public static class MyFlowAdapter extends IntegrationFlowAdapter {
...
    @Override
     protected IntegrationFlowDefinition<?> buildFlow() {
	...
   		.transform(this)
        ...
    }

    @Transformer
    public String transform(String payload, @Header("id") UUID id) {
	return payload.toLowerCase();
    }
...
}
```

Sorry, we can't help you without more context. That maybe is obvious for you. But for us you should prove the problem with some code, tests, stack traces etc. 

P.S. Please, take a looks into the formatting trick on [GitHub comments](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

P.S.S. GitHub issues are mostly for issues and improvement requests. Questions like yours must be placed on the [StackOverflow](http://stackoverflow.com) where any community member can help you.

**Comment by iainporter** [comment]
Sorry if I have posted an issue that is not an issue.

I have a test class that illustrates the failure for me

https://gist.github.com/iainporter/b0b034b369bd81f964a1e45b814cd831

**Comment by artembilan** [comment]
Thanks for sharing that one!
Your test works well for me.
I mean this code, of course:

```
@Bean
public IntegrationFlow pojoTransformFlow() {
	return f -> f
        	.enrichHeaders(h -> h.header("Foo", "Bar"))
            .transform(new PojoTransformer());
}
...
public static class PojoTransformer {

	@Transformer
	public String transform(String payload, @Header("Foo") String header) {
		return  payload + header;
	}

}
```
Not that commented in you Gist.

So, looks like you are using enough old Spring Integration Java DSL version.

Try with the latest `1.1.2`
Pay attention to the method I pointed above. It was introduced ` @since 1.1`

**Comment by iainporter** [comment]
gah. amateur's mistake.
It works with latest release.
Sorry for the waste of time.

**Comment by iainporter** [comment]
just to close this one off.
I eventually traced the problem to my header name having a dot i.e Foo.Bar
In the @Header annotation the property name is a SpEL expression which of course uses dot notation when parsing. 

See this example: https://gist.github.com/iainporter/8ec808e612afede998e54128ba36676e

**Comment by artembilan** [comment]
Yeah... I see the guilty code in the `MessagingMethodInvokerHelper.HandlerMethod`:
```
else if (valueAttribute.indexOf('.') != -1) {
	String[] tokens = valueAttribute.split("\\.", 2);
	headerName = tokens[0];
	if (StringUtils.hasText(tokens[1])) {
		relativeExpression = "." + tokens[1];
	}
}
...
String headerRetrievalExpression = "headers['" + headerName + "']";
String fullHeaderExpression = headerRetrievalExpression + relativeExpression;
```
Indeed it looks a bit ugly to reserve a `.` symbol and don't allow to have it as a part of custom header.

Not sure what we can do on the matter, but feel free to raise a [JIRA](https://jira.spring.io/browse/INT) and we may reconsider that in the future.
Maybe just drop that support because I wasn't able to find a description for that one. Unless some wrong JavaDoc:
```
* Annotation indicating that a method parameter's value should be
 * retrieved from the message headers. The value of the annotation
 * can either be a header name (e.g., 'foo') or SpEL expression
 * (e.g., 'payload.getCustomerId()') which is quite useful when
 * the name of the header has to be dynamically computed. It also
```
According to the parsing code above it won't work.
