### ISSUE TITLE
Add hook to easy configure IdempotentReceiver

### ISSUE THREAD

**Issue by artembilan** [spring-projects/spring-integration-java-dsl#92]
According to the [discussion](http://stackoverflow.com/questions/38150360/spring-idempotentreceiverinterceptor-can-only-be-used-on-messagehandlers), it looks like serendipity give the cue that `IdempotentReceiverInterceptor` should be configured like:
````
.transform(p -> p, c -> c.advice(this.idempotentReceiverInterceptor))
````
It really is inconvenient to deal with `@IdempotentReceiver`  from Java DSL perspective.
The Spring Integration issue on the matter: https://jira.spring.io/browse/INT-4064.
After that fix Java DSL 's`ConsumerEndpointSpec` should meet a new `adviceChain` logic via further population into the `ConsumerEndpointFactoryBean` independently of the `MessageHandler` type.

**Comment by asarkar** [comment]
@artembilan @garyrussell Is the proposed usage documented anywhere? I came across this ticket but can't find any code examples. The current [docs](https://docs.spring.io/spring-integration/reference/html/messaging-endpoints-chapter.html#idempotent-receiver) still show the annotation style:
```
@Bean
public IdempotentReceiverInterceptor idempotentReceiverInterceptor() {
   return new IdempotentReceiverInterceptor(new MetadataStoreSelector(m ->
                                                    m.getHeaders().get(INVOICE_NBR_HEADER)));
}

@Bean
@ServiceActivator(inputChannel = "input", outputChannel = "output")
@IdempotentReceiver("idempotentReceiverInterceptor")
public MessageHandler myService() {
    ....
}
```

**Comment by garyrussell** [comment]
@asarkar Since it is just an interceptor, it's simply defined as a `@Bean` and added to the endpoint's `.advice()` chain.

[You can see an example in this test case](https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/test/java/org/springframework/integration/dsl/transformers/TransformerTests.java#L313).

**Comment by asarkar** [comment]
For `handle`, the following matches the signature you show above
```
public <H extends MessageHandler> B handle(MessageHandlerSpec<?, H> messageHandlerSpec,
    Consumer<GenericEndpointSpec<H>> endpointConfigurer)
```

If the `advice` is an `IdempotentReceiverInterceptor` and returns `false` from its `MessageSelector`, does the `MessageHandler` still run? In other words, I'm trying to understand whether the idempotent receiver EAP needs to be applied before the handle step with a no-op transform/handle (as shown in the 1st post of this ticket), or can I apply it with the handle that actually does the work and the framework internally skips the handler if necessary?

**Comment by garyrussell** [comment]
[I pushed an example to the docs](https://github.com/spring-projects/spring-integration/commit/0245e7713639e2fffd5e717774f21986c26aa9d1); the advice chain in the endpoint spec for the `.handle()` itself applies to the current handler. So, no, you don't need another no-op spec.

**Comment by asarkar** [comment]
Thank you, that is helpful.
